spring:
  thymeleaf:
    cache: false

  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    driver-class-name: org.h2.Driver

my-env:
  first: ${FIRST_MALLANG_ENV}
  second: ${SECOND_MALLANG_ENV}
